### ISSUE TITLE
inkwell-http error

### ISSUE THREAD

**Issue by btam06** [dotink/inkwell-framework#6]
inkwell-http/src/Gateways/Server.php seems to be throwing an error that 'names' is an undefined index when running the fixfiles method.  Fresh install following quickstart guide.  init.php used as directory index.

**Comment by mattsah** [comment]
Should be fixed here: https://github.com/dotink/inkwell-http/commit/39765bea5cabdced9d32850465a5a0f1cf422e97

composer update
